### ISSUE TITLE
How to disable HID touch screen on bliss os

### ISSUE THREAD

**Issue by prilcool** [BlissRoms/platform_vendor_bliss#4]
Hi  
I am running blis os from usb live    all good.
I have case where dell laptop touch screen is faulty so i need the touch screen /Hid  to be off.

On linux I can disable it by editing the following conf file to stop the touch screen from working  :
VI /etc/modprobe.d/hid_multitouch.conf
blacklist hid_multitouch

How can I do this on bliss os  which file to edit and how to disable hid support.

**Comment by ericswpark** [comment]
Hi, this is the incorrect repo for Bliss OS support. This organization/repo is for BlissRoms, not Bliss OS. For help with Bliss OS, please use our official Telegram channels for help. Thanks!
